config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'users#index'

  resources :users do
    resources :messages
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :receiver, class_name: 'User', foreign_key: :receiver_id
  belongs_to :sender, class_name: 'User', foreign_key: :sender_id
  acts_as_paranoid
  paginates_per 5

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_paper_trail

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" },
                                      default_url: "/images/:style/noimg.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many :received_messages, class_name: 'Message', foreign_key: :receiver_id
  has_many :sent_messages, class_name: 'Message', foreign_key: :sender_id

  def age
    # unless date_of_birth

    #   now = Time.now.utc.to_date
    #   # binding.pry
    #   now.year - date_of_birth.year - (date_of_birth.to_date.change(:year => now.year) > now ? 1 : 0)
    # end
  end

  def self.search(search)
    if search !=nil or search.size !=0
      # binding.pry
      where("email like ?", search.chomp!)
    else
      User.all
    end

    # if search.size !=0 && search.size !=nil
    #   # binding.pry
    #   where("phone_number like ?", search)
    # else
    #   User.all
    # end


  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :address,
                                                              :phone_number, :email,
                                                               :avatar, :date_of_birth])
  end

  before_filter :set_paper_trail_whodunnit
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index

    @receiver_user = User.find(params[:user_id])

    # @messages = []#.page(params[:page])
    # binding.pry
    # unless current_user.sent_messages.empty?
    #   @messages += current_user.sent_messages.where(receiver: @receiver_user)#.to_ary
    # end
    # unless @receiver_user.sent_messages.empty?
    #   @messages += @receiver_user.sent_messages.where(receiver: current_user)#.to_ary
    # end
    messages_current_user = Message.where(sender_id: current_user.id,
                              receiver_id: @receiver_user.id)
    messages_current_receiver = Message.where(sender_id: @receiver_user.id,
                              receiver_id: current_user.id)
    # binding.pry
    @messages = (messages_current_user + messages_current_receiver).sort
    # binding.pry
    @messages = Kaminari.paginate_array(@messages).page(params[:page]).per(5)
# binding.pry
    # @messages = current_user.sent_messages.where(receiver_id: @receiver.id) +
    #             @receiver_user.sent_messages.where(receiver_id: current_user.id)
    # # end
    # @messages = @messages.page(params[:page])


    @message = Message.new
    # @messages =  Message.private_messages_array(@receiver.id)

  end

  def new
  end

  def create
   # binding.pry
    @message = Message.new(message_params)
    # # @message.receiver_id = params[:receiver_id]
    # @message.sender_id = current_user.id
    @message.save
    redirect_to user_messages_path #(receiver_id: @message.receiver_id), method: :get

  end

  def destroy
    # binding.pry
    message = Message.find_by(sender_id: params[:user_id], id: params[:id])
    message.destroy
    redirect_to :back
  end

  # def update
  #   message = Message.find()
  #   message.destroy
  #   redirect_to :back
  # end

  private

  def message_params
    params.require(:message).permit(:body,:sender_id,:receiver_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!

  def index
    # @users = User.all#.page(params[:page]).per(10)
    # binding.pry
    if params[:search]
      @users = User.search(params[:search])
    else
      @users = User.all
    end
  end

  def show
    # binding.pry
    @user = User.find(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalCoursesProj</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <%= image_tag current_user.avatar.url(:thumb) %>
  <strong>current user:</strong> <%= current_user.email %>

  <%= link_to "homepage", root_path %> |
  <%= link_to "show user profile", user_path(current_user) %> |
  <%= link_to "edit user profile", edit_user_registration_path %> |
    <%#= link_to "delete user", {controller:'devise/registrations', action: 'destroy'}, method: :delete %>
  <%= link_to "logout", destroy_user_session_path, method: :delete %>

  <p>
<% end %>


<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<strong>user</strong> <%= current_user.email %> <strong>chatting with</strong> <%= @receiver_user.email %>



<p>
<% if @messages %>
  <% @messages.sort.each do |message| %>
    <strong><%= message.sender.email %> wrote: </strong> <%= message.body %>
    <sub>at <%= time_ago_in_words(message.created_at) %></sub>
    <%# binding.pry %>
    <% if message.sender == current_user && message.deleted_at == nil %>
    <%= link_to 'delete msg', user_message_path(current_user.id,message.id), method: :delete %>
    <% end %>
    <br/>
  <% end %>
<% end %>
<p>
<%= paginate @messages %>
<p>
Put in new message:
<p>
<%= form_for @message, url: user_messages_path do |f| %>
  <%= f.text_field :body %>
  <%= f.hidden_field :receiver_id, { :value => @receiver_user.id } %>
  <%= f.hidden_field :sender_id, { :value => current_user.id } %>
  <%= f.submit "Send" %>
<% end %>

app/views/messages/new.html.erb
new.html.erb

app/views/messages/show.html.erb
show.html.erb

app/views/users/index.html.erb
<!-- List of all registered users
<p> -->

<%#= form_for @users, url: user_messages_path do |f| %>
  <%#= f.text_field :body %>
  <%# end %>
Find users by email
<%= form_tag root_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<% @users.each do |user| %>
  <strong>user id :</strong> <%= user.id %>,
  <strong> user email: </strong><%= user.email %>
  <%= link_to "<-> chat with", user_messages_url(user) unless user == current_user%> <br />
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>phone_number:</strong>
  <%= @user.phone_number %>
</p>
<p><p><p>
<strong>address:</strong>
  <%= @user.address %>
</p>
<p><p>
  <strong>age:</strong>
  <% if @user.date_of_birth? %>
    <%= @user.age %>
  <% end %>
</p>
<p>
  <strong>avatar:</strong>
  <%= image_tag @user.avatar.url %>
</p>